import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import JSZip from "jszip";
import { listIndexableFiles } from "../src/files";

test("listIndexableFiles includes text/code files and excludes built artifacts", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    await mkdir(path.join(root, "src"), { recursive: true });
    await mkdir(path.join(root, "dist"), { recursive: true });
    await mkdir(path.join(root, "public", "icons", "fonts"), { recursive: true });
    await mkdir(path.join(root, "packages", "site", "node_modules", "dep"), { recursive: true });
    await mkdir(path.join(root, "packages", "site", "dist"), { recursive: true });
    await mkdir(path.join(root, "packages", "site", "prisma", "migrations"), { recursive: true });
    await mkdir(path.join(root, ".agents", "skills"), { recursive: true });
    await mkdir(path.join(root, ".claude", "skills"), { recursive: true });
    await writeFile(path.join(root, "notes.md"), "# Notes\n", "utf8");
    await writeFile(path.join(root, "deck.pptx"), await makePptx("Deck text token"));
    await writeFile(path.join(root, "src", "index.ts"), "export const value = 1;\n", "utf8");
    await writeFile(path.join(root, "src", "routeTree.gen.ts"), "// generated route tree\n", "utf8");
    await writeFile(path.join(root, "src", "schema.generated.ts"), "// generated schema\n", "utf8");
    await writeFile(path.join(root, "dist", "bundle.js"), "generated();\n", "utf8");
    await writeFile(path.join(root, "worker-configuration.d.ts"), "// generated by wrangler\n", "utf8");
    await writeFile(path.join(root, "components.d.ts"), "// generated components\n", "utf8");
    await writeFile(path.join(root, "cloudflare-env.d.ts"), "// generated env\n", "utf8");
    await writeFile(path.join(root, "public", "icons", "demo.html"), "<!-- generated icomoon demo -->\n", "utf8");
    await writeFile(path.join(root, "public", "icons", "fonts", "icomoon.svg"), "<svg></svg>\n", "utf8");
    await writeFile(path.join(root, "public", "icons", "selection.json"), "{}\n", "utf8");
    await writeFile(path.join(root, "public", "icons", "style.css"), ".icon {}\n", "utf8");
    await writeFile(path.join(root, "packages", "site", "node_modules", "dep", "index.ts"), "export const dep = true;\n", "utf8");
    await writeFile(path.join(root, "packages", "site", "dist", "bundle.js"), "generated();\n", "utf8");
    await writeFile(path.join(root, "packages", "site", "prisma", "migrations", "migration_lock.toml"), "# generated by prisma\n", "utf8");
    await writeFile(path.join(root, "package-lock.json"), "{}\n", "utf8");
    await writeFile(path.join(root, ".env"), "TOKEN=secret\n", "utf8");
    await writeFile(path.join(root, ".env.local"), "TOKEN=secret\n", "utf8");
    await writeFile(path.join(root, "private.key"), "secret\n", "utf8");
    await writeFile(path.join(root, "id_ed25519"), "secret\n", "utf8");
    await writeFile(path.join(root, "pnpm-lock.yaml"), "lockfileVersion: 9\n", "utf8");
    await writeFile(path.join(root, "src", "Cargo.lock"), "# lock\n", "utf8");
    await writeFile(path.join(root, ".agents", "skills", "README.md"), "# Agent Skill\n", "utf8");
    await writeFile(path.join(root, ".claude", "skills", "README.md"), "# Claude Skill\n", "utf8");
    await writeFile(path.join(root, "image.png"), "not really an image", "utf8");

    const files = await listIndexableFiles(root, ".");
    assert.deepEqual(files.map((file) => file.relativePath), ["deck.pptx", "image.png", "notes.md", "src/index.ts"]);
    assert.match(files.find((file) => file.relativePath === "deck.pptx")?.content ?? "", /Deck text token/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("listIndexableFiles reads managed imports only when explicitly requested", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    const importRoot = path.join(root, ".kbx", "imports", "abc", "files");
    await mkdir(importRoot, { recursive: true });
    await writeFile(path.join(root, ".gitignore"), ".kbx/\n", "utf8");
    await writeFile(path.join(importRoot, "note.md"), "# Imported\n", "utf8");

    const workspaceScan = await listIndexableFiles(root, ".");
    assert.deepEqual(workspaceScan.map((file) => file.relativePath), []);

    const importScan = await listIndexableFiles(root, ".kbx/imports/abc/files", { includeKbxImports: true });
    assert.deepEqual(importScan.map((file) => file.relativePath), [".kbx/imports/abc/files/note.md"]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

async function makePptx(text: string): Promise<Buffer> {
  const zip = new JSZip();
  zip.folder("ppt")?.folder("slides")?.file("slide1.xml", `<?xml version="1.0" encoding="UTF-8"?>
<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
  <p:cSld><p:spTree><p:sp><p:txBody><a:p><a:r><a:t>${escapeXml(text)}</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld>
</p:sld>`);
  return zip.generateAsync({ type: "nodebuffer" });
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

test("listIndexableFiles reads managed session memories only when explicitly requested", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    const sessionRoot = path.join(root, ".kbx", "sessions");
    await mkdir(sessionRoot, { recursive: true });
    await writeFile(path.join(root, ".gitignore"), ".kbx/\n", "utf8");
    await writeFile(path.join(sessionRoot, "memory.md"), "# Memory\n", "utf8");

    const workspaceScan = await listIndexableFiles(root, ".");
    assert.deepEqual(workspaceScan.map((file) => file.relativePath), []);

    const sessionScan = await listIndexableFiles(root, ".kbx/sessions", { includeKbxSessions: true });
    assert.deepEqual(sessionScan.map((file) => file.relativePath), [".kbx/sessions/memory.md"]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("listIndexableFiles applies include, exclude, and gitignore overrides", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    await mkdir(path.join(root, "docs"), { recursive: true });
    await mkdir(path.join(root, "notes"), { recursive: true });
    await writeFile(path.join(root, ".gitignore"), "notes/\n", "utf8");
    await writeFile(path.join(root, "docs", "keep.md"), "# Keep\n", "utf8");
    await writeFile(path.join(root, "docs", "skip.md"), "# Skip\n", "utf8");
    await writeFile(path.join(root, "notes", "ignored.md"), "# Ignored\n", "utf8");

    const narrowed = await listIndexableFiles(root, ".", {
      include: ["docs/**"],
      exclude: ["docs/skip.md"]
    });
    assert.deepEqual(narrowed.map((file) => file.relativePath), ["docs/keep.md"]);

    const withoutGitignore = await listIndexableFiles(root, ".", { useGitignore: false });
    assert.equal(withoutGitignore.some((file) => file.relativePath === "notes/ignored.md"), true);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("listIndexableFiles applies root kbxignore in addition to gitignore", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    await mkdir(path.join(root, "docs"), { recursive: true });
    await mkdir(path.join(root, "screenshots"), { recursive: true });
    await writeFile(path.join(root, ".gitignore"), "notes/\n", "utf8");
    await writeFile(path.join(root, ".kbxignore"), "screenshots/**\nlarge-dump.json\n", "utf8");
    await writeFile(path.join(root, "docs", "keep.md"), "# Keep\n", "utf8");
    await writeFile(path.join(root, "screenshots", "ui.png"), "image bytes\n", "utf8");
    await writeFile(path.join(root, "large-dump.json"), "{}\n", "utf8");

    const files = await listIndexableFiles(root, ".");
    assert.deepEqual(files.map((file) => file.relativePath), ["docs/keep.md"]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("listIndexableFiles applies nested gitignore files", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    await mkdir(path.join(root, "docs"), { recursive: true });
    await writeFile(path.join(root, "docs", ".gitignore"), "private.md\n", "utf8");
    await writeFile(path.join(root, "docs", "public.md"), "# Public\n", "utf8");
    await writeFile(path.join(root, "docs", "private.md"), "# Private\n", "utf8");

    const files = await listIndexableFiles(root, ".");
    assert.deepEqual(files.map((file) => file.relativePath), ["docs/public.md"]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("listIndexableFiles does not follow symlinks outside the workspace", async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  const external = await mkdtemp(path.join(os.tmpdir(), "kbx-files-external-"));
  try {
    const linked = path.join(root, "linked");
    await writeFile(path.join(external, "outside.md"), "# Outside\n", "utf8");
    try {
      await symlink(external, linked, "junction");
    } catch (error) {
      t.skip(`symlink creation unavailable: ${error instanceof Error ? error.message : String(error)}`);
      return;
    }

    const files = await listIndexableFiles(root, ".");
    assert.equal(files.some((file) => file.relativePath === "linked/outside.md"), false);
  } finally {
    await rm(root, { recursive: true, force: true });
    await rm(external, { recursive: true, force: true });
  }
});

test("listIndexableFiles preserves gitignore negation patterns", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    await writeFile(path.join(root, ".gitignore"), "*.md\n!keep.md\n", "utf8");
    await writeFile(path.join(root, "keep.md"), "# Keep\n", "utf8");
    await writeFile(path.join(root, "skip.md"), "# Skip\n", "utf8");

    const files = await listIndexableFiles(root, ".");
    assert.deepEqual(files.map((file) => file.relativePath), ["keep.md"]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("listIndexableFiles pushes narrow includes into target-scoped scans", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kbx-files-"));
  try {
    await mkdir(path.join(root, "docs", "drafts"), { recursive: true });
    await mkdir(path.join(root, "docs", "nested"), { recursive: true });
    await mkdir(path.join(root, "src"), { recursive: true });
    await writeFile(path.join(root, "docs", "README.md"), "# Docs\n", "utf8");
    await writeFile(path.join(root, "docs", "nested", "README.md"), "# Nested\n", "utf8");
    await writeFile(path.join(root, "docs", "drafts", "README.md"), "# Draft\n", "utf8");
    await writeFile(path.join(root, "docs", "guide.md"), "# Guide\n", "utf8");
    await writeFile(path.join(root, "src", "README.md"), "# Src\n", "utf8");

    const docsReadmes = await listIndexableFiles(root, "docs", {
      include: ["README.md"],
      exclude: ["drafts/**"]
    });

    assert.deepEqual(docsReadmes.map((file) => file.relativePath), [
      "docs/README.md",
      "docs/nested/README.md"
    ]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
